var _ff = flipframe(showcaseSprite, x, y, image_xscale, image_yscale, 0, c_white, 1)
_ff.outline(c_pulse, 2.5)
draw_set_font(fnt_cosmicsans)
draw_set_halign(fa_center)
drawTextOutlined(x, y - 200, "Animation Type : " + stringifyAnimtype(Example.SCanimtype))
draw_set_halign(fa_right)
drawTextOutlined(x + 500, y - 200, "Current frame : " + string(showcaseSprite.get_subimage()))